module.exports = {
    name: "",
    version: "1.0.0",
    clientId: "",
    clientSecret: "",
    token: "",
    publicKey: "",
    permission: 141667724481,
    intents: 32767,
    prefix: "!",
    lang: "es",
    developers: [],
    invite: "",
    api: "http://localhost:3000/v1",
}